# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.image2.setFont(font)
        self.image2.setObjectName("image2")
        self.horizontalLayout_2.addWidget(self.image2)
        self.Add_image2 = QtWidgets.QPushButton(self.widget)
        self.Add_image2.setObjectName("Add_image2")
        self.horizontalLayout_2.addWidget(self.Add_image2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.view_image2 = ImageView(self.widget)
        self.view_image2.setObjectName("view_image2")
        self.verticalLayout_3.addWidget(self.view_image2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.image1.setFont(font)
        self.image1.setObjectName("image1")
        self.horizontalLayout.addWidget(self.image1)
        self.Add_image1 = QtWidgets.QPushButton(self.widget)
        self.Add_image1.setObjectName("Add_image1")
        self.horizontalLayout.addWidget(self.Add_image1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.view_image1 = ImageView(self.widget)
        self.view_image1.setObjectName("view_image1")
        self.verticalLayout.addWidget(self.view_image1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fourier1_combo = QtWidgets.QComboBox(self.widget1)
        self.fourier1_combo.setObjectName("fourier1_combo")
        self.fourier1_combo.addItem("")
        self.fourier1_combo.addItem("")
        self.fourier1_combo.addItem("")
        self.fourier1_combo.addItem("")
        self.verticalLayout_2.addWidget(self.fourier1_combo)
        self.view_fourier1 = ImageView(self.widget1)
        self.view_fourier1.setObjectName("view_fourier1")
        self.verticalLayout_2.addWidget(self.view_fourier1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fourier2_combo = QtWidgets.QComboBox(self.widget1)
        self.fourier2_combo.setObjectName("fourier2_combo")
        self.fourier2_combo.addItem("")
        self.fourier2_combo.addItem("")
        self.fourier2_combo.addItem("")
        self.fourier2_combo.addItem("")
        self.verticalLayout_4.addWidget(self.fourier2_combo)
        self.view_fourier2 = ImageView(self.widget1)
        self.view_fourier2.setObjectName("view_fourier2")
        self.verticalLayout_4.addWidget(self.view_fourier2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.widget2 = QtWidgets.QWidget(self.splitter_2)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mixer_widget = QtWidgets.QWidget(self.widget2)
        self.mixer_widget.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.mixer_widget.setObjectName("mixer_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.mixer_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.combonent12 = QtWidgets.QLabel(self.mixer_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.combonent12.setFont(font)
        self.combonent12.setObjectName("combonent12")
        self.gridLayout.addWidget(self.combonent12, 3, 0, 1, 1)
        self.componentBox_2 = QtWidgets.QComboBox(self.mixer_widget)
        self.componentBox_2.setObjectName("componentBox_2")
        self.componentBox_2.addItem("")
        self.componentBox_2.addItem("")
        self.gridLayout.addWidget(self.componentBox_2, 3, 1, 1, 2)
        self.select_modes2 = QtWidgets.QComboBox(self.mixer_widget)
        self.select_modes2.setObjectName("select_modes2")
        self.select_modes2.addItem("")
        self.select_modes2.addItem("")
        self.select_modes2.addItem("")
        self.select_modes2.addItem("")
        self.select_modes2.addItem("")
        self.select_modes2.addItem("")
        self.gridLayout.addWidget(self.select_modes2, 4, 0, 1, 1)
        self.slider2 = QtWidgets.QSlider(self.mixer_widget)
        self.slider2.setAutoFillBackground(False)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setInvertedAppearance(False)
        self.slider2.setInvertedControls(False)
        self.slider2.setObjectName("slider2")
        self.gridLayout.addWidget(self.slider2, 4, 2, 1, 1)
        self.slider2_label = QtWidgets.QLabel(self.mixer_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.slider2_label.setFont(font)
        self.slider2_label.setObjectName("slider2_label")
        self.gridLayout.addWidget(self.slider2_label, 4, 3, 1, 1)
        self.mixe_output = QtWidgets.QLabel(self.mixer_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mixe_output.setFont(font)
        self.mixe_output.setObjectName("mixe_output")
        self.gridLayout.addWidget(self.mixe_output, 0, 0, 1, 2)
        self.componentBox_1 = QtWidgets.QComboBox(self.mixer_widget)
        self.componentBox_1.setObjectName("componentBox_1")
        self.componentBox_1.addItem("")
        self.componentBox_1.addItem("")
        self.gridLayout.addWidget(self.componentBox_1, 1, 1, 1, 2)
        self.combonent1 = QtWidgets.QLabel(self.mixer_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.combonent1.setFont(font)
        self.combonent1.setObjectName("combonent1")
        self.gridLayout.addWidget(self.combonent1, 1, 0, 1, 1)
        self.slider1 = QtWidgets.QSlider(self.mixer_widget)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.gridLayout.addWidget(self.slider1, 2, 2, 1, 1)
        self.slider1_label = QtWidgets.QLabel(self.mixer_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.slider1_label.setFont(font)
        self.slider1_label.setObjectName("slider1_label")
        self.gridLayout.addWidget(self.slider1_label, 2, 3, 1, 1)
        self.outputBox = QtWidgets.QComboBox(self.mixer_widget)
        self.outputBox.setObjectName("outputBox")
        self.outputBox.addItem("")
        self.outputBox.addItem("")
        self.gridLayout.addWidget(self.outputBox, 0, 2, 1, 1)
        self.select_modes1 = QtWidgets.QComboBox(self.mixer_widget)
        self.select_modes1.setObjectName("select_modes1")
        self.select_modes1.addItem("")
        self.select_modes1.addItem("")
        self.select_modes1.addItem("")
        self.select_modes1.addItem("")
        self.select_modes1.addItem("")
        self.select_modes1.addItem("")
        self.gridLayout.addWidget(self.select_modes1, 2, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.mixer_widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.output1 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output1.setFont(font)
        self.output1.setObjectName("output1")
        self.verticalLayout_6.addWidget(self.output1)
        self.view_output1 = ImageView(self.widget2)
        self.view_output1.setObjectName("view_output1")
        self.verticalLayout_6.addWidget(self.view_output1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.output2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output2.setFont(font)
        self.output2.setObjectName("output2")
        self.verticalLayout_7.addWidget(self.output2)
        self.view_output2 = ImageView(self.widget2)
        self.view_output2.setObjectName("view_output2")
        self.verticalLayout_7.addWidget(self.view_output2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image2.setText(_translate("MainWindow", " Image2"))
        self.Add_image2.setText(_translate("MainWindow", "Add Image2"))
        self.image1.setText(_translate("MainWindow", " Image1"))
        self.Add_image1.setText(_translate("MainWindow", "Add Image1"))
        self.fourier1_combo.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.fourier1_combo.setItemText(1, _translate("MainWindow", "Phase"))
        self.fourier1_combo.setItemText(2, _translate("MainWindow", "Real"))
        self.fourier1_combo.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.fourier2_combo.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.fourier2_combo.setItemText(1, _translate("MainWindow", "Phase"))
        self.fourier2_combo.setItemText(2, _translate("MainWindow", "Real"))
        self.fourier2_combo.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.combonent12.setText(_translate("MainWindow", "Component2"))
        self.componentBox_2.setItemText(0, _translate("MainWindow", "Image 1"))
        self.componentBox_2.setItemText(1, _translate("MainWindow", "Image 2"))
        self.select_modes2.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.select_modes2.setItemText(1, _translate("MainWindow", "Uniform Magnitude"))
        self.select_modes2.setItemText(2, _translate("MainWindow", "Phase"))
        self.select_modes2.setItemText(3, _translate("MainWindow", "Uniform Phase"))
        self.select_modes2.setItemText(4, _translate("MainWindow", "Real"))
        self.select_modes2.setItemText(5, _translate("MainWindow", "Imaginary"))
        self.slider2_label.setText(_translate("MainWindow", "    0%"))
        self.mixe_output.setText(_translate("MainWindow", " Mixer Output to:"))
        self.componentBox_1.setItemText(0, _translate("MainWindow", "Image 1"))
        self.componentBox_1.setItemText(1, _translate("MainWindow", "Image 2"))
        self.combonent1.setText(_translate("MainWindow", "Component1"))
        self.slider1.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.slider1_label.setText(_translate("MainWindow", "    0%"))
        self.outputBox.setItemText(0, _translate("MainWindow", "Output 1"))
        self.outputBox.setItemText(1, _translate("MainWindow", "Output 2"))
        self.select_modes1.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.select_modes1.setItemText(1, _translate("MainWindow", "Uniform Magnitude"))
        self.select_modes1.setItemText(2, _translate("MainWindow", "Phase"))
        self.select_modes1.setItemText(3, _translate("MainWindow", "Uniform Phase"))
        self.select_modes1.setItemText(4, _translate("MainWindow", "Real"))
        self.select_modes1.setItemText(5, _translate("MainWindow", "Imaginary"))
        self.output1.setText(_translate("MainWindow", " output1"))
        self.output2.setText(_translate("MainWindow", " output2"))
from pyqtgraph import ImageView
