# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.view_1 = QtWidgets.QLabel(self.splitter_2)
        self.view_1.setText("")
        self.view_1.setObjectName("view_1")
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton_1 = QtWidgets.QPushButton(self.tab)
        self.startButton_1.setObjectName("startButton_1")
        self.horizontalLayout_2.addWidget(self.startButton_1)
        spacerItem = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stopButton_1 = QtWidgets.QPushButton(self.tab)
        self.stopButton_1.setObjectName("stopButton_1")
        self.horizontalLayout_2.addWidget(self.stopButton_1)
        spacerItem1 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ExportButton_1 = QtWidgets.QPushButton(self.tab)
        self.ExportButton_1.setObjectName("ExportButton_1")
        self.horizontalLayout_2.addWidget(self.ExportButton_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_5 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.sort_combo = QtWidgets.QComboBox(self.layoutWidget_3)
        self.sort_combo.setObjectName("sort_combo")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.sort_combo)
        self.view_2 = QtWidgets.QLabel(self.splitter_5)
        self.view_2.setText("")
        self.view_2.setObjectName("view_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.startButton_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.startButton_2.setObjectName("startButton_2")
        self.horizontalLayout_6.addWidget(self.startButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.stopButton_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.stopButton_2.setObjectName("stopButton_2")
        self.horizontalLayout_6.addWidget(self.stopButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.ExportButton_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.ExportButton_2.setObjectName("ExportButton_2")
        self.horizontalLayout_6.addWidget(self.ExportButton_2)
        self.gridLayout.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_4 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_4 = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.view_4 = QtWidgets.QLabel(self.splitter_4)
        self.view_4.setText("")
        self.view_4.setObjectName("view_4")
        self.verticalLayout_4.addWidget(self.splitter_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.startButton_4.setObjectName("startButton_4")
        self.horizontalLayout_4.addWidget(self.startButton_4)
        spacerItem5 = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.stopButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.stopButton_4.setObjectName("stopButton_4")
        self.horizontalLayout_4.addWidget(self.stopButton_4)
        spacerItem6 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.ExportButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.ExportButton_4.setObjectName("ExportButton_4")
        self.horizontalLayout_4.addWidget(self.ExportButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "              Covid-19 data visualization"))
        self.startButton_1.setText(_translate("MainWindow", "start"))
        self.stopButton_1.setText(_translate("MainWindow", "stop"))
        self.ExportButton_1.setText(_translate("MainWindow", "Export "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "A"))
        self.label_5.setText(_translate("MainWindow", "              Covid-19 data visualization"))
        self.sort_combo.setItemText(0, _translate("MainWindow", "Sort according to number of :"))
        self.sort_combo.setItemText(1, _translate("MainWindow", "Confirmed cases"))
        self.sort_combo.setItemText(2, _translate("MainWindow", "Deaths"))
        self.startButton_2.setText(_translate("MainWindow", "start"))
        self.stopButton_2.setText(_translate("MainWindow", "stop"))
        self.ExportButton_2.setText(_translate("MainWindow", "Export "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "C"))
        self.label_4.setText(_translate("MainWindow", "              Covid-19 data visualization"))
        self.startButton_4.setText(_translate("MainWindow", "start"))
        self.stopButton_4.setText(_translate("MainWindow", "stop"))
        self.ExportButton_4.setText(_translate("MainWindow", "Export "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "D"))
